export const data = [
    {
      checked: false,
      cust_name: "Andrea James",
      cust_no: 2523532,
      inv_no: 73457346735,
      inv_amnt: "122.87K",
      due_date: "23-Jan-2021",
      pred_date: "--",
      notes:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia adipisci quam iusto omnis eum, itaque optio eligendi veritatis ab dignissimos doloremque tempora nesciunt!",
    },
    {
      checked: false,
      cust_name: "Andrea James",
      cust_no: 2523532,
      inv_no: 73457346735,
      inv_amnt: "122.87K",
      due_date: "23-Jan-2021",
      pred_date: "--",
      notes:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia adipisci quam iusto omnis eum, itaque optio eligendi veritatis ab dignissimos doloremque tempora nesciunt!",
    },
    {
      checked: false,
      cust_name: "Andrea James",
      cust_no: 2523532,
      inv_no: 73457346735,
      inv_amnt: "122.87K",
      due_date: "23-Jan-2021",
      pred_date: "--",
      notes:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia adipisci quam iusto omnis eum, itaque optio eligendi veritatis ab dignissimos doloremque tempora nesciunt!",
    },
    {
      checked: false,
      cust_name: "Andrea James",
      cust_no: 2523532,
      inv_no: 73457346735,
      inv_amnt: "122.87K",
      due_date: "23-Jan-2021",
      pred_date: "--",
      notes:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia adipisci quam iusto omnis eum, itaque optio eligendi veritatis ab dignissimos doloremque tempora nesciunt!",
    },
    {
      checked: false,
      cust_name: "Andrea James",
      cust_no: 2523532,
      inv_no: 73457346735,
      inv_amnt: "122.87K",
      due_date: "23-Jan-2021",
      pred_date: "--",
      notes:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia adipisci quam iusto omnis eum, itaque optio eligendi veritatis ab dignissimos doloremque tempora nesciunt!",
    },
    {
      checked: false,
      cust_name: "Andrea James",
      cust_no: 2523532,
      inv_no: 73457346735,
      inv_amnt: "122.87K",
      due_date: "23-Jan-2021",
      pred_date: "--",
      notes:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia adipisci quam iusto omnis eum, itaque optio eligendi veritatis ab dignissimos doloremque tempora nesciunt!",
    },
    {
      checked: false,
      cust_name: "Andrea James",
      cust_no: 2523532,
      inv_no: 73457346735,
      inv_amnt: "122.87K",
      due_date: "23-Jan-2021",
      pred_date: "--",
      notes:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia adipisci quam iusto omnis eum, itaque optio eligendi veritatis ab dignissimos doloremque tempora nesciunt!",
    },
    {
      checked: false,
      cust_name: "Andrea James",
      cust_no: 2523532,
      inv_no: 73457346735,
      inv_amnt: "122.87K",
      due_date: "23-Jan-2021",
      pred_date: "--",
      notes:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia adipisci quam iusto omnis eum, itaque optio eligendi veritatis ab dignissimos doloremque tempora nesciunt!",
    },
    {
      checked: false,
      cust_name: "Andrea James",
      cust_no: 2523532,
      inv_no: 73457346735,
      inv_amnt: "122.87K",
      due_date: "23-Jan-2021",
      pred_date: "--",
      notes:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia adipisci quam iusto omnis eum, itaque optio eligendi veritatis ab dignissimos doloremque tempora nesciunt!",
    },
    {
      checked: false,
      cust_name: "Andrea James",
      cust_no: 2523532,
      inv_no: 73457346735,
      inv_amnt: "122.87K",
      due_date: "23-Jan-2021",
      pred_date: "--",
      notes:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia adipisci quam iusto omnis eum, itaque optio eligendi veritatis ab dignissimos doloremque tempora nesciunt!",
    },
    {
      checked: false,
      cust_name: "Andrea James",
      cust_no: 2523532,
      inv_no: 73457346735,
      inv_amnt: "122.87K",
      due_date: "23-Jan-2021",
      pred_date: "--",
      notes:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia adipisci quam iusto omnis eum, itaque optio eligendi veritatis ab dignissimos doloremque tempora nesciunt!",
    },
    {
      checked: false,
      cust_name: "Andrea James",
      cust_no: 2523532,
      inv_no: 73457346735,
      inv_amnt: "122.87K",
      due_date: "23-Jan-2021",
      pred_date: "--",
      notes:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia adipisci quam iusto omnis eum, itaque optio eligendi veritatis ab dignissimos doloremque tempora nesciunt!",
    },
    {
      checked: false,
      cust_name: "Andrea James",
      cust_no: 2523532,
      inv_no: 73457346735,
      inv_amnt: "122.87K",
      due_date: "23-Jan-2021",
      pred_date: "--",
      notes:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia adipisci quam iusto omnis eum, itaque optio eligendi veritatis ab dignissimos doloremque tempora nesciunt!",
    },
    {
      checked: false,
      cust_name: "Andrea James",
      cust_no: 2523532,
      inv_no: 73457346735,
      inv_amnt: "122.87K",
      due_date: "23-Jan-2021",
      pred_date: "--",
      notes:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia adipisci quam iusto omnis eum, itaque optio eligendi veritatis ab dignissimos doloremque tempora nesciunt!",
    },
  ];